services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-wallet}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-api:
    build: ./core-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-wallet}
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD:-root}
      AWS_S3_ENDPOINT: http://s3-local:9090
      AWS_S3_PUBLIC_URL: http://localhost:9000
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME:-wallet}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY:-test}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY:-test}
    depends_on:
      mysql:
        condition: service_healthy
      s3-local:
        condition: service_started

  ai-worker:
    build: ./ai-worker
    environment:
      GEMINI_KEY: ${GEMINI_KEY}
    depends_on:
      - core-api

  s3-local:
    image: adobe/s3mock:latest
    container_name: local-s3-mock
    ports:
      - "9000:9090"
    environment:
      - initialBuckets=${AWS_BUCKET_NAME}

volumes:
  mysql_data:
